# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: postgres
#   password: postgres
#   host: localhost

# development:
#   <<: *default
#   database: caregivers_development

# test:
#   <<: *default  
#   database: caregivers_test

production:
  adapter: postgresql
  username: szdyhwxaxjmqqo
  password: 73dd164ec2115dac2caad65b1de6e3fca2a3dcc8fabd49268285f65255ec48a4
  host: ec2-54-83-40-208.compute-1.amazonaws.com
  port: 5432
  database: daa61moe26nh49


